# Generated by Django 4.2.13 on 2024-05-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userfriendmapper"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="fullname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
