# Generated by Django 4.2.13 on 2024-05-16 04:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_user_username_user_fullname"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfriendmapper",
            unique_together={("user", "friend")},
        ),
    ]
